deepseek:
  api-url: https://api.deepseek.com/v1/chat/completions
  api-key: ${DEEPSEEK_API_KEY:sk-5edbfb6f77bf4bd2bb79037ebaac30c0}
  model: deepseek-chat
  temperature: 0.0

spring:
  datasource:
    url: jdbc:h2:file:./data/mecdb;AUTO_SERVER=TRUE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

mec:
  llm:
    active: DEEPSEEK
    models:
      CHATGPT:
        api-url: https://api.openai.com/v1/chat/completions
        api-key: sk-yourkey
        model-name: gpt-4o
        temperature: 0.0
      DEEPSEEK:
        api-url: https://api.deepseek.com/v1/chat/completions
        api-key: ${DEEPSEEK_API_KEY:sk-5edbfb6f77bf4bd2bb79037ebaac30c0}
        model-name: deepseek-chat
        temperature: 0.0
